import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Newsreader } from "next/font/google";
import {
    NavigationMenu,
    NavigationMenuContent,
    NavigationMenuIndicator,
    NavigationMenuItem,
    NavigationMenuLink,
    NavigationMenuList,
    NavigationMenuTrigger,
    NavigationMenuViewport,
} from "@/components/ui/navigation-menu"



const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});


const newsReader = Newsreader({
    variable: "--font-newsreader",
    subsets: ["latin"]
})
export const metadata: Metadata = {
    title: "Vega",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html className={newsReader.className} lang="en">
            <body className="dark">
                <nav
                    className="flex items-center p-4 border-b border-border/50 sticky top-0 z-50"
                    style={{ background: "var(--background)" }}
                >
                    <div className="text-2xl font-bold text-foreground mr-8">VEGA</div>
                    <div className="flex-1 flex justify-center">
                        <NavigationMenu className="flex">
                            <NavigationMenuList className="flex space-x-8">
                                <NavigationMenuItem>
                                    <NavigationMenuLink className="text-foreground hover:text-primary">Home</NavigationMenuLink>
                                </NavigationMenuItem>
                                <NavigationMenuItem>
                                    <NavigationMenuLink className="text-foreground hover:text-primary">About</NavigationMenuLink>
                                </NavigationMenuItem>
                                <NavigationMenuItem>
                                    <NavigationMenuLink className="text-foreground hover:text-primary">Pricing</NavigationMenuLink>
                                </NavigationMenuItem>
                            </NavigationMenuList>
                        </NavigationMenu>
                    </div>
                </nav>
                {children}
            </body>
        </html>
    );
}
