import type { Metadata } from "next";
import {Exo_2 } from "next/font/google";
import "./globals.css";
import { Newsreader } from "next/font/google";
import {
    NavigationMenu,
    NavigationMenuContent,
    NavigationMenuIndicator,
    NavigationMenuItem,
    NavigationMenuLink,
    NavigationMenuList,
    NavigationMenuTrigger,
    NavigationMenuViewport,
} from "@/components/ui/navigation-menu"

const exo_2 = Exo_2({
    variable: "--font-exo-2",
    subsets: ["latin"],
    weight: ["400", "700"]
});

const newsReader = Newsreader({
    variable: "--font-newsreader",
    subsets: ["latin"]
})
export const metadata: Metadata = {
    title: "Vega",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html className={exo_2.className} lang="en">
            <body className="dark">
                <nav
                    className="flex items-center p-4 sticky top-0 z-50"
                    style={{ background: "var(--background)", borderBottom: "1px solid #E0E2DB" }}
                >
                    <div className="text-4xl font-bold mr-8" style={{ color: "#E0E2DB" }}>VEGA</div>
                    <div className="flex-1 flex justify-center">
                        <NavigationMenu className="flex justify-center w-full">
                            <NavigationMenuList className="flex space-x-8 justify-center w-full">
                                <NavigationMenuItem>
                                    <NavigationMenuLink className="hover:text-primary text-2xl" style={{ color: "#E0E2DB" }}>Home</NavigationMenuLink>
                                </NavigationMenuItem>
                                <NavigationMenuItem>
                                    <NavigationMenuLink className="hover:text-primary text-2xl" style={{ color: "#E0E2DB" }}>About</NavigationMenuLink>
                                </NavigationMenuItem>
                                <NavigationMenuItem>
                                    <NavigationMenuLink className="hover:text-primary text-2xl" style={{ color: "#E0E2DB" }}>Pricing</NavigationMenuLink>
                                </NavigationMenuItem>
                            </NavigationMenuList>
                        </NavigationMenu>
                    </div>
                    <div className="flex items-center justify-end min-w-[120px]">
                        <NavigationMenu className="flex">
                            <NavigationMenuList className="flex">
                                <NavigationMenuItem>
                                    <NavigationMenuLink className="hover:text-primary text-2xl" style={{ color: "#E0E2DB" }}>Account</NavigationMenuLink>
                                </NavigationMenuItem>
                            </NavigationMenuList>
                        </NavigationMenu>
                    </div>
                </nav>
                {children}
            </body>
        </html>
    );
}
